# Generated by Django 5.1.2 on 2024-12-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='reg_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('viewer', 'Viewer'), ('client', 'Client')], default='user', max_length=10),
        ),
    ]
