# Generated by Django 5.1.2 on 2024-12-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_blogs_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='author',
            new_name='author_id',
        ),
        migrations.AddField(
            model_name='blogs',
            name='author_name',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
