# Generated by Django 5.1.2 on 2024-12-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_register_bio_register_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogs',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
